# Generated by Django 4.2.6 on 2024-02-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
