# Generated by Django 5.0.1 on 2024-03-14 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_order_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('offer_valid_amount', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
