# Generated by Django 5.0.1 on 2024-04-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
