# Generated by Django 4.2.6 on 2024-02-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id']},
        ),
    ]
