# Generated by Django 5.0.1 on 2024-02-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={},
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', related_query_name='custom_user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', related_query_name='custom_user', to='auth.permission'),
        ),
    ]
